# CSFLE2 consumer with BOTH KEKs (PII + PCI).
# All tagged fields decrypt to plaintext.
bootstrap.servers=${BOOTSTRAP_SERVERS}
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CSFLE2_CONSUMER_BOTH_KAFKA_API_KEY}" password="${CSFLE2_CONSUMER_BOTH_KAFKA_API_SECRET}";

group.id=demo-csfle2-both
auto.offset.reset=earliest

schema.registry.url=${SR_URL}
basic.auth.credentials.source=USER_INFO
basic.auth.user.info=${CSFLE2_CONSUMER_BOTH_SR_API_KEY}:${CSFLE2_CONSUMER_BOTH_SR_API_SECRET}
use.latest.version=true

rule.executors=_default_
rule.executors._default_.class=io.confluent.kafka.schemaregistry.encryption.FieldEncryptionExecutor
